move models to own files/simplify view
brainglobe/brainrender-napari pull request #123
Opened 2023-12-18 15:33 UTC by alessandrofelder

## Description

**What is this PR**

- [ ] Bug fix
- [x] Addition of a new feature
- [ ] Other

**Why is this PR needed?**

It is a step on the way towards being able to download new atlases, and update local atlases to newer versions, through a napari GUI.

**What does this PR do?**

## References

Please reference any existing issues/PRs that relate to this PR.

## How has this PR been tested?

Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.

## Is this a breaking change?

If this PR breaks any existing functionality, please explain how and why.

## Does this PR require an update to the documentation?

If any features have changed, or have been added. Please explain how the documentation has been updated (and link to the associated PR). See [here](https://docs.cellfinder.info/for-developers/documentation) for details.

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [ ] The code has been formatted with [pre-commit](https://pre-commit.com/)

2023-12-19 09:15 UTC, alessandrofelder commented on brainrender_napari/data_models/atlas_table_model.py
> +        return " ".join([formatted for formatted in formatted_name])
These are the new functions added to the atlas table model.

2023-12-20 14:22 UTC, IgorTatarnikov requested changes
Looks good, just a few comments on my end!

2023-12-20 15:48 UTC, alessandrofelder commented on brainrender_napari/widgets/atlas_viewer_view.py
> +            self.hideColumn(hidden_column)
Good point - I can implement this with a simple refactor of our custom model.

2023-12-20 16:01 UTC, alessandrofelder commented on brainrender_napari/data_models/atlas_table_model.py
> +                )
Don't think it currently returns something sensible unfortunately - I've tested locally and it gives a list index out of range error. I've opened https://github.com/brainglobe/bg-atlasapi/issues/187 as a possibility for the future.

2023-12-20 17:03 UTC, IgorTatarnikov approved these changes
Looks good 👍

2023-12-20 17:03 UTC, merged